version: '3.4'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "9080:9080"
  sync:
  	restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.sync
    ports:
      - "9090:9090"
    volumes:
      - ./builds/server:/usr/app/tec/server/-
